### ISSUE TITLE
Fix the missing files

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-web#5]
```
  - source: /lang/en/obf/texts/mobile-app-open-beauty-facts.html
    translation: /lang/%two_letters_code%/obf/texts/mobile-app-open-beauty-facts.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl-NL: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /openfoodfacts-server/madenearme/madenearme-world.html
    translation: /openfoodfacts-server/madenearme/madenearme_%two_letters_code%.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl-NL: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /lang/obf/en/texts/data.en.html
    translation: /lang/obf/%two_letters_code%/texts/data.en.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl-NL: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
  - source: /lang/en/texts/donate.html
    translation: /lang/%two_letters_code%/texts/donate.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl-NL: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
```

**Comment by teolemon** [comment]
```
  - source: /html/donate/en.html
    translation: /html/donate/%two_letters_code%.html
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
        zh-CN: zh_CN
        en-AU: en_AU
        en-GB: en_GB
        pt-BR: pt_BR
        pt-PT: pt_PT
        nl-BE: nl_BE
        nl-NL: nl_NL
        zh-TW: zh_TW
        sr-CS: sr_CS
        sr: sr_RS
        ku : kmr_TR
        kmr: kmr
```
